import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    max: 52,
    min: 1,
    total: 4777,
    githubTotal: 1521,
    codeTotal: 3256,
    year: '2022',
    days: [
      {
        week: 2,
        days: [
          {
            date: '2022-01-02',
            day: 0,
            month: 1,
            total: 0,
            week: 2,
            year: 2022,
            count: 6,
            codeCount: 0,
            githubCount: 6,
          },
          {
            date: '2022-01-03',
            day: 1,
            month: 1,
            total: 1,
            week: 2,
            year: 2022,
            count: 11,
            codeCount: 1,
            githubCount: 10,
          },
          {
            date: '2022-01-04',
            day: 2,
            month: 1,
            total: 55,
            week: 2,
            year: 2022,
            count: 67,
            codeCount: 55,
            githubCount: 12,
          },
          {
            date: '2022-01-05',
            day: 3,
            month: 1,
            total: 36,
            week: 2,
            year: 2022,
            count: 40,
            codeCount: 36,
            githubCount: 4,
          },
          {
            date: '2022-01-06',
            day: 4,
            month: 1,
            total: 11,
            week: 2,
            year: 2022,
            count: 11,
            codeCount: 11,
            githubCount: 0,
          },
          {
            date: '2022-01-07',
            day: 5,
            month: 1,
            total: 0,
            week: 2,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-01-08',
            day: 6,
            month: 1,
            total: 0,
            week: 2,
            year: 2022,
            count: 8,
            codeCount: 0,
            githubCount: 8,
          },
        ],
      },
      {
        week: 3,
        days: [
          {
            date: '2022-01-09',
            day: 0,
            month: 1,
            total: 0,
            week: 3,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-01-10',
            day: 1,
            month: 1,
            total: 2,
            week: 3,
            year: 2022,
            count: 13,
            codeCount: 2,
            githubCount: 11,
          },
          {
            date: '2022-01-11',
            day: 2,
            month: 1,
            total: 0,
            week: 3,
            year: 2022,
            count: 6,
            codeCount: 0,
            githubCount: 6,
          },
          {
            date: '2022-01-12',
            day: 3,
            month: 1,
            total: 5,
            week: 3,
            year: 2022,
            count: 8,
            codeCount: 5,
            githubCount: 3,
          },
          {
            date: '2022-01-13',
            day: 4,
            month: 1,
            total: 1,
            week: 3,
            year: 2022,
            count: 2,
            codeCount: 1,
            githubCount: 1,
          },
          {
            date: '2022-01-14',
            day: 5,
            month: 1,
            total: 19,
            week: 3,
            year: 2022,
            count: 29,
            codeCount: 19,
            githubCount: 10,
          },
          {
            date: '2022-01-15',
            day: 6,
            month: 1,
            total: 0,
            week: 3,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 4,
        days: [
          {
            date: '2022-01-16',
            day: 0,
            month: 1,
            total: 0,
            week: 4,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-01-17',
            day: 1,
            month: 1,
            total: 3,
            week: 4,
            year: 2022,
            count: 7,
            codeCount: 3,
            githubCount: 4,
          },
          {
            date: '2022-01-18',
            day: 2,
            month: 1,
            total: 0,
            week: 4,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-01-19',
            day: 3,
            month: 1,
            total: 6,
            week: 4,
            year: 2022,
            count: 7,
            codeCount: 6,
            githubCount: 1,
          },
          {
            date: '2022-01-20',
            day: 4,
            month: 1,
            total: 4,
            week: 4,
            year: 2022,
            count: 5,
            codeCount: 4,
            githubCount: 1,
          },
          {
            date: '2022-01-21',
            day: 5,
            month: 1,
            total: 0,
            week: 4,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-01-22',
            day: 6,
            month: 1,
            total: 0,
            week: 4,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 5,
        days: [
          {
            date: '2022-01-23',
            day: 0,
            month: 1,
            total: 0,
            week: 5,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-01-24',
            day: 1,
            month: 1,
            total: 8,
            week: 5,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
          {
            date: '2022-01-25',
            day: 2,
            month: 1,
            total: 20,
            week: 5,
            year: 2022,
            count: 21,
            codeCount: 20,
            githubCount: 1,
          },
          {
            date: '2022-01-26',
            day: 3,
            month: 1,
            total: 16,
            week: 5,
            year: 2022,
            count: 16,
            codeCount: 16,
            githubCount: 0,
          },
          {
            date: '2022-01-27',
            day: 4,
            month: 1,
            total: 0,
            week: 5,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-01-28',
            day: 5,
            month: 1,
            total: 6,
            week: 5,
            year: 2022,
            count: 6,
            codeCount: 6,
            githubCount: 0,
          },
          {
            date: '2022-01-29',
            day: 6,
            month: 1,
            total: 0,
            week: 5,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
        ],
      },
      {
        week: 6,
        days: [
          {
            date: '2022-01-30',
            day: 0,
            month: 1,
            total: 1,
            week: 6,
            year: 2022,
            count: 6,
            codeCount: 1,
            githubCount: 5,
          },
          {
            date: '2022-01-31',
            day: 1,
            month: 1,
            total: 0,
            week: 6,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-02-01',
            day: 2,
            month: 2,
            total: 0,
            week: 6,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
          {
            date: '2022-02-02',
            day: 3,
            month: 2,
            total: 0,
            week: 6,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-02-03',
            day: 4,
            month: 2,
            total: 0,
            week: 6,
            year: 2022,
            count: 10,
            codeCount: 0,
            githubCount: 10,
          },
          {
            date: '2022-02-04',
            day: 5,
            month: 2,
            total: 0,
            week: 6,
            year: 2022,
            count: 8,
            codeCount: 0,
            githubCount: 8,
          },
          {
            date: '2022-02-05',
            day: 6,
            month: 2,
            total: 1,
            week: 6,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
        ],
      },
      {
        week: 7,
        days: [
          {
            date: '2022-02-06',
            day: 0,
            month: 2,
            total: 2,
            week: 7,
            year: 2022,
            count: 2,
            codeCount: 2,
            githubCount: 0,
          },
          {
            date: '2022-02-07',
            day: 1,
            month: 2,
            total: 0,
            week: 7,
            year: 2022,
            count: 9,
            codeCount: 0,
            githubCount: 9,
          },
          {
            date: '2022-02-08',
            day: 2,
            month: 2,
            total: 3,
            week: 7,
            year: 2022,
            count: 8,
            codeCount: 3,
            githubCount: 5,
          },
          {
            date: '2022-02-09',
            day: 3,
            month: 2,
            total: 0,
            week: 7,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-02-10',
            day: 4,
            month: 2,
            total: 1,
            week: 7,
            year: 2022,
            count: 2,
            codeCount: 1,
            githubCount: 1,
          },
          {
            date: '2022-02-11',
            day: 5,
            month: 2,
            total: 4,
            week: 7,
            year: 2022,
            count: 7,
            codeCount: 4,
            githubCount: 3,
          },
          {
            date: '2022-02-12',
            day: 6,
            month: 2,
            total: 0,
            week: 7,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 8,
        days: [
          {
            date: '2022-02-13',
            day: 0,
            month: 2,
            total: 0,
            week: 8,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-02-14',
            day: 1,
            month: 2,
            total: 0,
            week: 8,
            year: 2022,
            count: 8,
            codeCount: 0,
            githubCount: 8,
          },
          {
            date: '2022-02-15',
            day: 2,
            month: 2,
            total: 13,
            week: 8,
            year: 2022,
            count: 15,
            codeCount: 13,
            githubCount: 2,
          },
          {
            date: '2022-02-16',
            day: 3,
            month: 2,
            total: 18,
            week: 8,
            year: 2022,
            count: 19,
            codeCount: 18,
            githubCount: 1,
          },
          {
            date: '2022-02-17',
            day: 4,
            month: 2,
            total: 8,
            week: 8,
            year: 2022,
            count: 13,
            codeCount: 8,
            githubCount: 5,
          },
          {
            date: '2022-02-18',
            day: 5,
            month: 2,
            total: 4,
            week: 8,
            year: 2022,
            count: 5,
            codeCount: 4,
            githubCount: 1,
          },
          {
            date: '2022-02-19',
            day: 6,
            month: 2,
            total: 0,
            week: 8,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 9,
        days: [
          {
            date: '2022-02-20',
            day: 0,
            month: 2,
            total: 0,
            week: 9,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-02-21',
            day: 1,
            month: 2,
            total: 4,
            week: 9,
            year: 2022,
            count: 13,
            codeCount: 4,
            githubCount: 9,
          },
          {
            date: '2022-02-22',
            day: 2,
            month: 2,
            total: 0,
            week: 9,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-02-23',
            day: 3,
            month: 2,
            total: 0,
            week: 9,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-02-24',
            day: 4,
            month: 2,
            total: 3,
            week: 9,
            year: 2022,
            count: 9,
            codeCount: 3,
            githubCount: 6,
          },
          {
            date: '2022-02-25',
            day: 5,
            month: 2,
            total: 0,
            week: 9,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-02-26',
            day: 6,
            month: 2,
            total: 0,
            week: 9,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
        ],
      },
      {
        week: 10,
        days: [
          {
            date: '2022-02-27',
            day: 0,
            month: 2,
            total: 0,
            week: 10,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-02-28',
            day: 1,
            month: 2,
            total: 1,
            week: 10,
            year: 2022,
            count: 23,
            codeCount: 1,
            githubCount: 22,
          },
          {
            date: '2022-03-01',
            day: 2,
            month: 3,
            total: 2,
            week: 10,
            year: 2022,
            count: 9,
            codeCount: 2,
            githubCount: 7,
          },
          {
            date: '2022-03-02',
            day: 3,
            month: 3,
            total: 5,
            week: 10,
            year: 2022,
            count: 24,
            codeCount: 5,
            githubCount: 19,
          },
          {
            date: '2022-03-03',
            day: 4,
            month: 3,
            total: 25,
            week: 10,
            year: 2022,
            count: 34,
            codeCount: 25,
            githubCount: 9,
          },
          {
            date: '2022-03-04',
            day: 5,
            month: 3,
            total: 8,
            week: 10,
            year: 2022,
            count: 12,
            codeCount: 8,
            githubCount: 4,
          },
          {
            date: '2022-03-05',
            day: 6,
            month: 3,
            total: 0,
            week: 10,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 11,
        days: [
          {
            date: '2022-03-06',
            day: 0,
            month: 3,
            total: 0,
            week: 11,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-03-07',
            day: 1,
            month: 3,
            total: 5,
            week: 11,
            year: 2022,
            count: 25,
            codeCount: 5,
            githubCount: 20,
          },
          {
            date: '2022-03-08',
            day: 2,
            month: 3,
            total: 0,
            week: 11,
            year: 2022,
            count: 9,
            codeCount: 0,
            githubCount: 9,
          },
          {
            date: '2022-03-09',
            day: 3,
            month: 3,
            total: 3,
            week: 11,
            year: 2022,
            count: 19,
            codeCount: 3,
            githubCount: 16,
          },
          {
            date: '2022-03-10',
            day: 4,
            month: 3,
            total: 2,
            week: 11,
            year: 2022,
            count: 3,
            codeCount: 2,
            githubCount: 1,
          },
          {
            date: '2022-03-11',
            day: 5,
            month: 3,
            total: 4,
            week: 11,
            year: 2022,
            count: 15,
            codeCount: 4,
            githubCount: 11,
          },
          {
            date: '2022-03-12',
            day: 6,
            month: 3,
            total: 0,
            week: 11,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 12,
        days: [
          {
            date: '2022-03-13',
            day: 0,
            month: 3,
            total: 0,
            week: 12,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-03-14',
            day: 1,
            month: 3,
            total: 22,
            week: 12,
            year: 2022,
            count: 29,
            codeCount: 22,
            githubCount: 7,
          },
          {
            date: '2022-03-15',
            day: 2,
            month: 3,
            total: 61,
            week: 12,
            year: 2022,
            count: 66,
            codeCount: 61,
            githubCount: 5,
          },
          {
            date: '2022-03-16',
            day: 3,
            month: 3,
            total: 3,
            week: 12,
            year: 2022,
            count: 7,
            codeCount: 3,
            githubCount: 4,
          },
          {
            date: '2022-03-17',
            day: 4,
            month: 3,
            total: 0,
            week: 12,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-03-18',
            day: 5,
            month: 3,
            total: 8,
            week: 12,
            year: 2022,
            count: 16,
            codeCount: 8,
            githubCount: 8,
          },
          {
            date: '2022-03-19',
            day: 6,
            month: 3,
            total: 0,
            week: 12,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
        ],
      },
      {
        week: 13,
        days: [
          {
            date: '2022-03-20',
            day: 0,
            month: 3,
            total: 0,
            week: 13,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-03-21',
            day: 1,
            month: 3,
            total: 11,
            week: 13,
            year: 2022,
            count: 16,
            codeCount: 11,
            githubCount: 5,
          },
          {
            date: '2022-03-22',
            day: 2,
            month: 3,
            total: 35,
            week: 13,
            year: 2022,
            count: 36,
            codeCount: 35,
            githubCount: 1,
          },
          {
            date: '2022-03-23',
            day: 3,
            month: 3,
            total: 12,
            week: 13,
            year: 2022,
            count: 14,
            codeCount: 12,
            githubCount: 2,
          },
          {
            date: '2022-03-24',
            day: 4,
            month: 3,
            total: 11,
            week: 13,
            year: 2022,
            count: 12,
            codeCount: 11,
            githubCount: 1,
          },
          {
            date: '2022-03-25',
            day: 5,
            month: 3,
            total: 14,
            week: 13,
            year: 2022,
            count: 16,
            codeCount: 14,
            githubCount: 2,
          },
          {
            date: '2022-03-26',
            day: 6,
            month: 3,
            total: 2,
            week: 13,
            year: 2022,
            count: 8,
            codeCount: 2,
            githubCount: 6,
          },
        ],
      },
      {
        week: 14,
        days: [
          {
            date: '2022-03-27',
            day: 0,
            month: 3,
            total: 0,
            week: 14,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-03-28',
            day: 1,
            month: 3,
            total: 11,
            week: 14,
            year: 2022,
            count: 12,
            codeCount: 11,
            githubCount: 1,
          },
          {
            date: '2022-03-29',
            day: 2,
            month: 3,
            total: 2,
            week: 14,
            year: 2022,
            count: 2,
            codeCount: 2,
            githubCount: 0,
          },
          {
            date: '2022-03-30',
            day: 3,
            month: 3,
            total: 4,
            week: 14,
            year: 2022,
            count: 12,
            codeCount: 4,
            githubCount: 8,
          },
          {
            date: '2022-03-31',
            day: 4,
            month: 3,
            total: 26,
            week: 14,
            year: 2022,
            count: 38,
            codeCount: 26,
            githubCount: 12,
          },
          {
            date: '2022-04-01',
            day: 5,
            month: 4,
            total: 1,
            week: 14,
            year: 2022,
            count: 10,
            codeCount: 1,
            githubCount: 9,
          },
          {
            date: '2022-04-02',
            day: 6,
            month: 4,
            total: 3,
            week: 14,
            year: 2022,
            count: 7,
            codeCount: 3,
            githubCount: 4,
          },
        ],
      },
      {
        week: 15,
        days: [
          {
            date: '2022-04-03',
            day: 0,
            month: 4,
            total: 0,
            week: 15,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-04-04',
            day: 1,
            month: 4,
            total: 0,
            week: 15,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-04-05',
            day: 2,
            month: 4,
            total: 0,
            week: 15,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
          {
            date: '2022-04-06',
            day: 3,
            month: 4,
            total: 10,
            week: 15,
            year: 2022,
            count: 22,
            codeCount: 10,
            githubCount: 12,
          },
          {
            date: '2022-04-07',
            day: 4,
            month: 4,
            total: 9,
            week: 15,
            year: 2022,
            count: 21,
            codeCount: 9,
            githubCount: 12,
          },
          {
            date: '2022-04-08',
            day: 5,
            month: 4,
            total: 5,
            week: 15,
            year: 2022,
            count: 7,
            codeCount: 5,
            githubCount: 2,
          },
          {
            date: '2022-04-09',
            day: 6,
            month: 4,
            total: 0,
            week: 15,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 16,
        days: [
          {
            date: '2022-04-10',
            day: 0,
            month: 4,
            total: 0,
            week: 16,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-04-11',
            day: 1,
            month: 4,
            total: 1,
            week: 16,
            year: 2022,
            count: 8,
            codeCount: 1,
            githubCount: 7,
          },
          {
            date: '2022-04-12',
            day: 2,
            month: 4,
            total: 1,
            week: 16,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
          {
            date: '2022-04-13',
            day: 3,
            month: 4,
            total: 12,
            week: 16,
            year: 2022,
            count: 13,
            codeCount: 12,
            githubCount: 1,
          },
          {
            date: '2022-04-14',
            day: 4,
            month: 4,
            total: 0,
            week: 16,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-04-15',
            day: 5,
            month: 4,
            total: 5,
            week: 16,
            year: 2022,
            count: 8,
            codeCount: 5,
            githubCount: 3,
          },
          {
            date: '2022-04-16',
            day: 6,
            month: 4,
            total: 0,
            week: 16,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
        ],
      },
      {
        week: 17,
        days: [
          {
            date: '2022-04-17',
            day: 0,
            month: 4,
            total: 0,
            week: 17,
            year: 2022,
            count: 6,
            codeCount: 0,
            githubCount: 6,
          },
          {
            date: '2022-04-18',
            day: 1,
            month: 4,
            total: 23,
            week: 17,
            year: 2022,
            count: 35,
            codeCount: 23,
            githubCount: 12,
          },
          {
            date: '2022-04-19',
            day: 2,
            month: 4,
            total: 7,
            week: 17,
            year: 2022,
            count: 7,
            codeCount: 7,
            githubCount: 0,
          },
          {
            date: '2022-04-20',
            day: 3,
            month: 4,
            total: 31,
            week: 17,
            year: 2022,
            count: 35,
            codeCount: 31,
            githubCount: 4,
          },
          {
            date: '2022-04-21',
            day: 4,
            month: 4,
            total: 0,
            week: 17,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-04-22',
            day: 5,
            month: 4,
            total: 9,
            week: 17,
            year: 2022,
            count: 12,
            codeCount: 9,
            githubCount: 3,
          },
          {
            date: '2022-04-23',
            day: 6,
            month: 4,
            total: 0,
            week: 17,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 18,
        days: [
          {
            date: '2022-04-24',
            day: 0,
            month: 4,
            total: 23,
            week: 18,
            year: 2022,
            count: 24,
            codeCount: 23,
            githubCount: 1,
          },
          {
            date: '2022-04-25',
            day: 1,
            month: 4,
            total: 16,
            week: 18,
            year: 2022,
            count: 16,
            codeCount: 16,
            githubCount: 0,
          },
          {
            date: '2022-04-26',
            day: 2,
            month: 4,
            total: 8,
            week: 18,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
          {
            date: '2022-04-27',
            day: 3,
            month: 4,
            total: 8,
            week: 18,
            year: 2022,
            count: 9,
            codeCount: 8,
            githubCount: 1,
          },
          {
            date: '2022-04-28',
            day: 4,
            month: 4,
            total: 2,
            week: 18,
            year: 2022,
            count: 3,
            codeCount: 2,
            githubCount: 1,
          },
          {
            date: '2022-04-29',
            day: 5,
            month: 4,
            total: 21,
            week: 18,
            year: 2022,
            count: 22,
            codeCount: 21,
            githubCount: 1,
          },
          {
            date: '2022-04-30',
            day: 6,
            month: 4,
            total: 0,
            week: 18,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
        ],
      },
      {
        week: 19,
        days: [
          {
            date: '2022-05-01',
            day: 0,
            month: 5,
            total: 3,
            week: 19,
            year: 2022,
            count: 5,
            codeCount: 3,
            githubCount: 2,
          },
          {
            date: '2022-05-02',
            day: 1,
            month: 5,
            total: 0,
            week: 19,
            year: 2022,
            count: 12,
            codeCount: 0,
            githubCount: 12,
          },
          {
            date: '2022-05-03',
            day: 2,
            month: 5,
            total: 0,
            week: 19,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
          {
            date: '2022-05-04',
            day: 3,
            month: 5,
            total: 0,
            week: 19,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-05-05',
            day: 4,
            month: 5,
            total: 19,
            week: 19,
            year: 2022,
            count: 27,
            codeCount: 19,
            githubCount: 8,
          },
          {
            date: '2022-05-06',
            day: 5,
            month: 5,
            total: 34,
            week: 19,
            year: 2022,
            count: 36,
            codeCount: 34,
            githubCount: 2,
          },
          {
            date: '2022-05-07',
            day: 6,
            month: 5,
            total: 8,
            week: 19,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
        ],
      },
      {
        week: 20,
        days: [
          {
            date: '2022-05-08',
            day: 0,
            month: 5,
            total: 0,
            week: 20,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-05-09',
            day: 1,
            month: 5,
            total: 23,
            week: 20,
            year: 2022,
            count: 26,
            codeCount: 23,
            githubCount: 3,
          },
          {
            date: '2022-05-10',
            day: 2,
            month: 5,
            total: 16,
            week: 20,
            year: 2022,
            count: 23,
            codeCount: 16,
            githubCount: 7,
          },
          {
            date: '2022-05-11',
            day: 3,
            month: 5,
            total: 21,
            week: 20,
            year: 2022,
            count: 37,
            codeCount: 21,
            githubCount: 16,
          },
          {
            date: '2022-05-12',
            day: 4,
            month: 5,
            total: 33,
            week: 20,
            year: 2022,
            count: 36,
            codeCount: 33,
            githubCount: 3,
          },
          {
            date: '2022-05-13',
            day: 5,
            month: 5,
            total: 33,
            week: 20,
            year: 2022,
            count: 50,
            codeCount: 33,
            githubCount: 17,
          },
          {
            date: '2022-05-14',
            day: 6,
            month: 5,
            total: 0,
            week: 20,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
        ],
      },
      {
        week: 21,
        days: [
          {
            date: '2022-05-15',
            day: 0,
            month: 5,
            total: 10,
            week: 21,
            year: 2022,
            count: 11,
            codeCount: 10,
            githubCount: 1,
          },
          {
            date: '2022-05-16',
            day: 1,
            month: 5,
            total: 20,
            week: 21,
            year: 2022,
            count: 23,
            codeCount: 20,
            githubCount: 3,
          },
          {
            date: '2022-05-17',
            day: 2,
            month: 5,
            total: 27,
            week: 21,
            year: 2022,
            count: 31,
            codeCount: 27,
            githubCount: 4,
          },
          {
            date: '2022-05-18',
            day: 3,
            month: 5,
            total: 33,
            week: 21,
            year: 2022,
            count: 34,
            codeCount: 33,
            githubCount: 1,
          },
          {
            date: '2022-05-19',
            day: 4,
            month: 5,
            total: 21,
            week: 21,
            year: 2022,
            count: 31,
            codeCount: 21,
            githubCount: 10,
          },
          {
            date: '2022-05-20',
            day: 5,
            month: 5,
            total: 25,
            week: 21,
            year: 2022,
            count: 29,
            codeCount: 25,
            githubCount: 4,
          },
          {
            date: '2022-05-21',
            day: 6,
            month: 5,
            total: 1,
            week: 21,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
        ],
      },
      {
        week: 22,
        days: [
          {
            date: '2022-05-22',
            day: 0,
            month: 5,
            total: 0,
            week: 22,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-05-23',
            day: 1,
            month: 5,
            total: 51,
            week: 22,
            year: 2022,
            count: 62,
            codeCount: 51,
            githubCount: 11,
          },
          {
            date: '2022-05-24',
            day: 2,
            month: 5,
            total: 14,
            week: 22,
            year: 2022,
            count: 21,
            codeCount: 14,
            githubCount: 7,
          },
          {
            date: '2022-05-25',
            day: 3,
            month: 5,
            total: 13,
            week: 22,
            year: 2022,
            count: 14,
            codeCount: 13,
            githubCount: 1,
          },
          {
            date: '2022-05-26',
            day: 4,
            month: 5,
            total: 3,
            week: 22,
            year: 2022,
            count: 7,
            codeCount: 3,
            githubCount: 4,
          },
          {
            date: '2022-05-27',
            day: 5,
            month: 5,
            total: 16,
            week: 22,
            year: 2022,
            count: 16,
            codeCount: 16,
            githubCount: 0,
          },
          {
            date: '2022-05-28',
            day: 6,
            month: 5,
            total: 0,
            week: 22,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 23,
        days: [
          {
            date: '2022-05-29',
            day: 0,
            month: 5,
            total: 0,
            week: 23,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-05-30',
            day: 1,
            month: 5,
            total: 13,
            week: 23,
            year: 2022,
            count: 13,
            codeCount: 13,
            githubCount: 0,
          },
          {
            date: '2022-05-31',
            day: 2,
            month: 5,
            total: 0,
            week: 23,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-06-01',
            day: 3,
            month: 6,
            total: 6,
            week: 23,
            year: 2022,
            count: 8,
            codeCount: 6,
            githubCount: 2,
          },
          {
            date: '2022-06-02',
            day: 4,
            month: 6,
            total: 3,
            week: 23,
            year: 2022,
            count: 10,
            codeCount: 3,
            githubCount: 7,
          },
          {
            date: '2022-06-03',
            day: 5,
            month: 6,
            total: 0,
            week: 23,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-06-04',
            day: 6,
            month: 6,
            total: 0,
            week: 23,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 24,
        days: [
          {
            date: '2022-06-05',
            day: 0,
            month: 6,
            total: 0,
            week: 24,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-06-06',
            day: 1,
            month: 6,
            total: 3,
            week: 24,
            year: 2022,
            count: 13,
            codeCount: 3,
            githubCount: 10,
          },
          {
            date: '2022-06-07',
            day: 2,
            month: 6,
            total: 4,
            week: 24,
            year: 2022,
            count: 8,
            codeCount: 4,
            githubCount: 4,
          },
          {
            date: '2022-06-08',
            day: 3,
            month: 6,
            total: 0,
            week: 24,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-06-09',
            day: 4,
            month: 6,
            total: 9,
            week: 24,
            year: 2022,
            count: 20,
            codeCount: 9,
            githubCount: 11,
          },
          {
            date: '2022-06-10',
            day: 5,
            month: 6,
            total: 8,
            week: 24,
            year: 2022,
            count: 10,
            codeCount: 8,
            githubCount: 2,
          },
          {
            date: '2022-06-11',
            day: 6,
            month: 6,
            total: 0,
            week: 24,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
        ],
      },
      {
        week: 25,
        days: [
          {
            date: '2022-06-12',
            day: 0,
            month: 6,
            total: 0,
            week: 25,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-06-13',
            day: 1,
            month: 6,
            total: 11,
            week: 25,
            year: 2022,
            count: 35,
            codeCount: 11,
            githubCount: 24,
          },
          {
            date: '2022-06-14',
            day: 2,
            month: 6,
            total: 10,
            week: 25,
            year: 2022,
            count: 18,
            codeCount: 10,
            githubCount: 8,
          },
          {
            date: '2022-06-15',
            day: 3,
            month: 6,
            total: 8,
            week: 25,
            year: 2022,
            count: 10,
            codeCount: 8,
            githubCount: 2,
          },
          {
            date: '2022-06-16',
            day: 4,
            month: 6,
            total: 7,
            week: 25,
            year: 2022,
            count: 11,
            codeCount: 7,
            githubCount: 4,
          },
          {
            date: '2022-06-17',
            day: 5,
            month: 6,
            total: 13,
            week: 25,
            year: 2022,
            count: 14,
            codeCount: 13,
            githubCount: 1,
          },
          {
            date: '2022-06-18',
            day: 6,
            month: 6,
            total: 3,
            week: 25,
            year: 2022,
            count: 4,
            codeCount: 3,
            githubCount: 1,
          },
        ],
      },
      {
        week: 26,
        days: [
          {
            date: '2022-06-19',
            day: 0,
            month: 6,
            total: 4,
            week: 26,
            year: 2022,
            count: 11,
            codeCount: 4,
            githubCount: 7,
          },
          {
            date: '2022-06-20',
            day: 1,
            month: 6,
            total: 26,
            week: 26,
            year: 2022,
            count: 50,
            codeCount: 26,
            githubCount: 24,
          },
          {
            date: '2022-06-21',
            day: 2,
            month: 6,
            total: 30,
            week: 26,
            year: 2022,
            count: 41,
            codeCount: 30,
            githubCount: 11,
          },
          {
            date: '2022-06-22',
            day: 3,
            month: 6,
            total: 15,
            week: 26,
            year: 2022,
            count: 23,
            codeCount: 15,
            githubCount: 8,
          },
          {
            date: '2022-06-23',
            day: 4,
            month: 6,
            total: 42,
            week: 26,
            year: 2022,
            count: 52,
            codeCount: 42,
            githubCount: 10,
          },
          {
            date: '2022-06-24',
            day: 5,
            month: 6,
            total: 29,
            week: 26,
            year: 2022,
            count: 38,
            codeCount: 29,
            githubCount: 9,
          },
          {
            date: '2022-06-25',
            day: 6,
            month: 6,
            total: 0,
            week: 26,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 27,
        days: [
          {
            date: '2022-06-26',
            day: 0,
            month: 6,
            total: 0,
            week: 27,
            year: 2022,
            count: 8,
            codeCount: 0,
            githubCount: 8,
          },
          {
            date: '2022-06-27',
            day: 1,
            month: 6,
            total: 18,
            week: 27,
            year: 2022,
            count: 27,
            codeCount: 18,
            githubCount: 9,
          },
          {
            date: '2022-06-28',
            day: 2,
            month: 6,
            total: 9,
            week: 27,
            year: 2022,
            count: 29,
            codeCount: 9,
            githubCount: 20,
          },
          {
            date: '2022-06-29',
            day: 3,
            month: 6,
            total: 12,
            week: 27,
            year: 2022,
            count: 34,
            codeCount: 12,
            githubCount: 22,
          },
          {
            date: '2022-06-30',
            day: 4,
            month: 6,
            total: 21,
            week: 27,
            year: 2022,
            count: 36,
            codeCount: 21,
            githubCount: 15,
          },
          {
            date: '2022-07-01',
            day: 5,
            month: 7,
            total: 12,
            week: 27,
            year: 2022,
            count: 14,
            codeCount: 12,
            githubCount: 2,
          },
          {
            date: '2022-07-02',
            day: 6,
            month: 7,
            total: 0,
            week: 27,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 28,
        days: [
          {
            date: '2022-07-03',
            day: 0,
            month: 7,
            total: 0,
            week: 28,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-07-04',
            day: 1,
            month: 7,
            total: 7,
            week: 28,
            year: 2022,
            count: 20,
            codeCount: 7,
            githubCount: 13,
          },
          {
            date: '2022-07-05',
            day: 2,
            month: 7,
            total: 0,
            week: 28,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
          {
            date: '2022-07-06',
            day: 3,
            month: 7,
            total: 3,
            week: 28,
            year: 2022,
            count: 8,
            codeCount: 3,
            githubCount: 5,
          },
          {
            date: '2022-07-07',
            day: 4,
            month: 7,
            total: 4,
            week: 28,
            year: 2022,
            count: 10,
            codeCount: 4,
            githubCount: 6,
          },
          {
            date: '2022-07-08',
            day: 5,
            month: 7,
            total: 1,
            week: 28,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
          {
            date: '2022-07-09',
            day: 6,
            month: 7,
            total: 0,
            week: 28,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 29,
        days: [
          {
            date: '2022-07-10',
            day: 0,
            month: 7,
            total: 0,
            week: 29,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-07-11',
            day: 1,
            month: 7,
            total: 3,
            week: 29,
            year: 2022,
            count: 8,
            codeCount: 3,
            githubCount: 5,
          },
          {
            date: '2022-07-12',
            day: 2,
            month: 7,
            total: 0,
            week: 29,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-07-13',
            day: 3,
            month: 7,
            total: 3,
            week: 29,
            year: 2022,
            count: 10,
            codeCount: 3,
            githubCount: 7,
          },
          {
            date: '2022-07-14',
            day: 4,
            month: 7,
            total: 0,
            week: 29,
            year: 2022,
            count: 18,
            codeCount: 0,
            githubCount: 18,
          },
          {
            date: '2022-07-15',
            day: 5,
            month: 7,
            total: 0,
            week: 29,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-07-16',
            day: 6,
            month: 7,
            total: 0,
            week: 29,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 30,
        days: [
          {
            date: '2022-07-17',
            day: 0,
            month: 7,
            total: 0,
            week: 30,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-07-18',
            day: 1,
            month: 7,
            total: 0,
            week: 30,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-07-19',
            day: 2,
            month: 7,
            total: 2,
            week: 30,
            year: 2022,
            count: 32,
            codeCount: 2,
            githubCount: 30,
          },
          {
            date: '2022-07-20',
            day: 3,
            month: 7,
            total: 19,
            week: 30,
            year: 2022,
            count: 32,
            codeCount: 19,
            githubCount: 13,
          },
          {
            date: '2022-07-21',
            day: 4,
            month: 7,
            total: 3,
            week: 30,
            year: 2022,
            count: 46,
            codeCount: 3,
            githubCount: 43,
          },
          {
            date: '2022-07-22',
            day: 5,
            month: 7,
            total: 39,
            week: 30,
            year: 2022,
            count: 48,
            codeCount: 39,
            githubCount: 9,
          },
          {
            date: '2022-07-23',
            day: 6,
            month: 7,
            total: 0,
            week: 30,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 31,
        days: [
          {
            date: '2022-07-24',
            day: 0,
            month: 7,
            total: 0,
            week: 31,
            year: 2022,
            count: 5,
            codeCount: 0,
            githubCount: 5,
          },
          {
            date: '2022-07-25',
            day: 1,
            month: 7,
            total: 15,
            week: 31,
            year: 2022,
            count: 18,
            codeCount: 15,
            githubCount: 3,
          },
          {
            date: '2022-07-26',
            day: 2,
            month: 7,
            total: 29,
            week: 31,
            year: 2022,
            count: 33,
            codeCount: 29,
            githubCount: 4,
          },
          {
            date: '2022-07-27',
            day: 3,
            month: 7,
            total: 18,
            week: 31,
            year: 2022,
            count: 20,
            codeCount: 18,
            githubCount: 2,
          },
          {
            date: '2022-07-28',
            day: 4,
            month: 7,
            total: 15,
            week: 31,
            year: 2022,
            count: 18,
            codeCount: 15,
            githubCount: 3,
          },
          {
            date: '2022-07-29',
            day: 5,
            month: 7,
            total: 9,
            week: 31,
            year: 2022,
            count: 9,
            codeCount: 9,
            githubCount: 0,
          },
          {
            date: '2022-07-30',
            day: 6,
            month: 7,
            total: 0,
            week: 31,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 32,
        days: [
          {
            date: '2022-07-31',
            day: 0,
            month: 7,
            total: 0,
            week: 32,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-08-01',
            day: 1,
            month: 8,
            total: 9,
            week: 32,
            year: 2022,
            count: 16,
            codeCount: 9,
            githubCount: 7,
          },
          {
            date: '2022-08-02',
            day: 2,
            month: 8,
            total: 2,
            week: 32,
            year: 2022,
            count: 2,
            codeCount: 2,
            githubCount: 0,
          },
          {
            date: '2022-08-03',
            day: 3,
            month: 8,
            total: 3,
            week: 32,
            year: 2022,
            count: 3,
            codeCount: 3,
            githubCount: 0,
          },
          {
            date: '2022-08-04',
            day: 4,
            month: 8,
            total: 15,
            week: 32,
            year: 2022,
            count: 15,
            codeCount: 15,
            githubCount: 0,
          },
          {
            date: '2022-08-05',
            day: 5,
            month: 8,
            total: 11,
            week: 32,
            year: 2022,
            count: 11,
            codeCount: 11,
            githubCount: 0,
          },
          {
            date: '2022-08-06',
            day: 6,
            month: 8,
            total: 0,
            week: 32,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 33,
        days: [
          {
            date: '2022-08-07',
            day: 0,
            month: 8,
            total: 0,
            week: 33,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-08-08',
            day: 1,
            month: 8,
            total: 4,
            week: 33,
            year: 2022,
            count: 14,
            codeCount: 4,
            githubCount: 10,
          },
          {
            date: '2022-08-09',
            day: 2,
            month: 8,
            total: 7,
            week: 33,
            year: 2022,
            count: 7,
            codeCount: 7,
            githubCount: 0,
          },
          {
            date: '2022-08-10',
            day: 3,
            month: 8,
            total: 11,
            week: 33,
            year: 2022,
            count: 11,
            codeCount: 11,
            githubCount: 0,
          },
          {
            date: '2022-08-11',
            day: 4,
            month: 8,
            total: 10,
            week: 33,
            year: 2022,
            count: 10,
            codeCount: 10,
            githubCount: 0,
          },
          {
            date: '2022-08-12',
            day: 5,
            month: 8,
            total: 6,
            week: 33,
            year: 2022,
            count: 9,
            codeCount: 6,
            githubCount: 3,
          },
          {
            date: '2022-08-13',
            day: 6,
            month: 8,
            total: 0,
            week: 33,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
        ],
      },
      {
        week: 34,
        days: [
          {
            date: '2022-08-14',
            day: 0,
            month: 8,
            total: 0,
            week: 34,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-08-15',
            day: 1,
            month: 8,
            total: 28,
            week: 34,
            year: 2022,
            count: 38,
            codeCount: 28,
            githubCount: 10,
          },
          {
            date: '2022-08-16',
            day: 2,
            month: 8,
            total: 15,
            week: 34,
            year: 2022,
            count: 19,
            codeCount: 15,
            githubCount: 4,
          },
          {
            date: '2022-08-17',
            day: 3,
            month: 8,
            total: 19,
            week: 34,
            year: 2022,
            count: 24,
            codeCount: 19,
            githubCount: 5,
          },
          {
            date: '2022-08-18',
            day: 4,
            month: 8,
            total: 11,
            week: 34,
            year: 2022,
            count: 20,
            codeCount: 11,
            githubCount: 9,
          },
          {
            date: '2022-08-19',
            day: 5,
            month: 8,
            total: 5,
            week: 34,
            year: 2022,
            count: 8,
            codeCount: 5,
            githubCount: 3,
          },
          {
            date: '2022-08-20',
            day: 6,
            month: 8,
            total: 0,
            week: 34,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
        ],
      },
      {
        week: 35,
        days: [
          {
            date: '2022-08-21',
            day: 0,
            month: 8,
            total: 0,
            week: 35,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-08-22',
            day: 1,
            month: 8,
            total: 6,
            week: 35,
            year: 2022,
            count: 13,
            codeCount: 6,
            githubCount: 7,
          },
          {
            date: '2022-08-23',
            day: 2,
            month: 8,
            total: 3,
            week: 35,
            year: 2022,
            count: 6,
            codeCount: 3,
            githubCount: 3,
          },
          {
            date: '2022-08-24',
            day: 3,
            month: 8,
            total: 22,
            week: 35,
            year: 2022,
            count: 22,
            codeCount: 22,
            githubCount: 0,
          },
          {
            date: '2022-08-25',
            day: 4,
            month: 8,
            total: 7,
            week: 35,
            year: 2022,
            count: 13,
            codeCount: 7,
            githubCount: 6,
          },
          {
            date: '2022-08-26',
            day: 5,
            month: 8,
            total: 6,
            week: 35,
            year: 2022,
            count: 14,
            codeCount: 6,
            githubCount: 8,
          },
          {
            date: '2022-08-27',
            day: 6,
            month: 8,
            total: 10,
            week: 35,
            year: 2022,
            count: 10,
            codeCount: 10,
            githubCount: 0,
          },
        ],
      },
      {
        week: 36,
        days: [
          {
            date: '2022-08-28',
            day: 0,
            month: 8,
            total: 0,
            week: 36,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-08-29',
            day: 1,
            month: 8,
            total: 12,
            week: 36,
            year: 2022,
            count: 17,
            codeCount: 12,
            githubCount: 5,
          },
          {
            date: '2022-08-30',
            day: 2,
            month: 8,
            total: 6,
            week: 36,
            year: 2022,
            count: 12,
            codeCount: 6,
            githubCount: 6,
          },
          {
            date: '2022-08-31',
            day: 3,
            month: 8,
            total: 5,
            week: 36,
            year: 2022,
            count: 8,
            codeCount: 5,
            githubCount: 3,
          },
          {
            date: '2022-09-01',
            day: 4,
            month: 9,
            total: 3,
            week: 36,
            year: 2022,
            count: 7,
            codeCount: 3,
            githubCount: 4,
          },
          {
            date: '2022-09-02',
            day: 5,
            month: 9,
            total: 13,
            week: 36,
            year: 2022,
            count: 21,
            codeCount: 13,
            githubCount: 8,
          },
          {
            date: '2022-09-03',
            day: 6,
            month: 9,
            total: 0,
            week: 36,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 37,
        days: [
          {
            date: '2022-09-04',
            day: 0,
            month: 9,
            total: 5,
            week: 37,
            year: 2022,
            count: 12,
            codeCount: 5,
            githubCount: 7,
          },
          {
            date: '2022-09-05',
            day: 1,
            month: 9,
            total: 34,
            week: 37,
            year: 2022,
            count: 44,
            codeCount: 34,
            githubCount: 10,
          },
          {
            date: '2022-09-06',
            day: 2,
            month: 9,
            total: 13,
            week: 37,
            year: 2022,
            count: 17,
            codeCount: 13,
            githubCount: 4,
          },
          {
            date: '2022-09-07',
            day: 3,
            month: 9,
            total: 30,
            week: 37,
            year: 2022,
            count: 44,
            codeCount: 30,
            githubCount: 14,
          },
          {
            date: '2022-09-08',
            day: 4,
            month: 9,
            total: 32,
            week: 37,
            year: 2022,
            count: 36,
            codeCount: 32,
            githubCount: 4,
          },
          {
            date: '2022-09-09',
            day: 5,
            month: 9,
            total: 14,
            week: 37,
            year: 2022,
            count: 18,
            codeCount: 14,
            githubCount: 4,
          },
          {
            date: '2022-09-10',
            day: 6,
            month: 9,
            total: 0,
            week: 37,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 38,
        days: [
          {
            date: '2022-09-11',
            day: 0,
            month: 9,
            total: 0,
            week: 38,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-09-12',
            day: 1,
            month: 9,
            total: 0,
            week: 38,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-09-13',
            day: 2,
            month: 9,
            total: 10,
            week: 38,
            year: 2022,
            count: 17,
            codeCount: 10,
            githubCount: 7,
          },
          {
            date: '2022-09-14',
            day: 3,
            month: 9,
            total: 29,
            week: 38,
            year: 2022,
            count: 34,
            codeCount: 29,
            githubCount: 5,
          },
          {
            date: '2022-09-15',
            day: 4,
            month: 9,
            total: 3,
            week: 38,
            year: 2022,
            count: 9,
            codeCount: 3,
            githubCount: 6,
          },
          {
            date: '2022-09-16',
            day: 5,
            month: 9,
            total: 10,
            week: 38,
            year: 2022,
            count: 14,
            codeCount: 10,
            githubCount: 4,
          },
          {
            date: '2022-09-17',
            day: 6,
            month: 9,
            total: 0,
            week: 38,
            year: 2022,
            count: 7,
            codeCount: 0,
            githubCount: 7,
          },
        ],
      },
      {
        week: 39,
        days: [
          {
            date: '2022-09-18',
            day: 0,
            month: 9,
            total: 0,
            week: 39,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-09-19',
            day: 1,
            month: 9,
            total: 16,
            week: 39,
            year: 2022,
            count: 16,
            codeCount: 16,
            githubCount: 0,
          },
          {
            date: '2022-09-20',
            day: 2,
            month: 9,
            total: 15,
            week: 39,
            year: 2022,
            count: 15,
            codeCount: 15,
            githubCount: 0,
          },
          {
            date: '2022-09-21',
            day: 3,
            month: 9,
            total: 2,
            week: 39,
            year: 2022,
            count: 5,
            codeCount: 2,
            githubCount: 3,
          },
          {
            date: '2022-09-22',
            day: 4,
            month: 9,
            total: 28,
            week: 39,
            year: 2022,
            count: 29,
            codeCount: 28,
            githubCount: 1,
          },
          {
            date: '2022-09-23',
            day: 5,
            month: 9,
            total: 1,
            week: 39,
            year: 2022,
            count: 3,
            codeCount: 1,
            githubCount: 2,
          },
          {
            date: '2022-09-24',
            day: 6,
            month: 9,
            total: 6,
            week: 39,
            year: 2022,
            count: 7,
            codeCount: 6,
            githubCount: 1,
          },
        ],
      },
      {
        week: 40,
        days: [
          {
            date: '2022-09-25',
            day: 0,
            month: 9,
            total: 0,
            week: 40,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-09-26',
            day: 1,
            month: 9,
            total: 82,
            week: 40,
            year: 2022,
            count: 82,
            codeCount: 82,
            githubCount: 0,
          },
          {
            date: '2022-09-27',
            day: 2,
            month: 9,
            total: 75,
            week: 40,
            year: 2022,
            count: 76,
            codeCount: 75,
            githubCount: 1,
          },
          {
            date: '2022-09-28',
            day: 3,
            month: 9,
            total: 59,
            week: 40,
            year: 2022,
            count: 59,
            codeCount: 59,
            githubCount: 0,
          },
          {
            date: '2022-09-29',
            day: 4,
            month: 9,
            total: 1,
            week: 40,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
          {
            date: '2022-09-30',
            day: 5,
            month: 9,
            total: 0,
            week: 40,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-10-01',
            day: 6,
            month: 10,
            total: 0,
            week: 40,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 41,
        days: [
          {
            date: '2022-10-02',
            day: 0,
            month: 10,
            total: 0,
            week: 41,
            year: 2022,
            count: 8,
            codeCount: 0,
            githubCount: 8,
          },
          {
            date: '2022-10-03',
            day: 1,
            month: 10,
            total: 0,
            week: 41,
            year: 2022,
            count: 6,
            codeCount: 0,
            githubCount: 6,
          },
          {
            date: '2022-10-04',
            day: 2,
            month: 10,
            total: 0,
            week: 41,
            year: 2022,
            count: 9,
            codeCount: 0,
            githubCount: 9,
          },
          {
            date: '2022-10-05',
            day: 3,
            month: 10,
            total: 3,
            week: 41,
            year: 2022,
            count: 5,
            codeCount: 3,
            githubCount: 2,
          },
          {
            date: '2022-10-06',
            day: 4,
            month: 10,
            total: 15,
            week: 41,
            year: 2022,
            count: 27,
            codeCount: 15,
            githubCount: 12,
          },
          {
            date: '2022-10-07',
            day: 5,
            month: 10,
            total: 3,
            week: 41,
            year: 2022,
            count: 19,
            codeCount: 3,
            githubCount: 16,
          },
          {
            date: '2022-10-08',
            day: 6,
            month: 10,
            total: 26,
            week: 41,
            year: 2022,
            count: 26,
            codeCount: 26,
            githubCount: 0,
          },
        ],
      },
      {
        week: 42,
        days: [
          {
            date: '2022-10-09',
            day: 0,
            month: 10,
            total: 8,
            week: 42,
            year: 2022,
            count: 11,
            codeCount: 8,
            githubCount: 3,
          },
          {
            date: '2022-10-10',
            day: 1,
            month: 10,
            total: 14,
            week: 42,
            year: 2022,
            count: 17,
            codeCount: 14,
            githubCount: 3,
          },
          {
            date: '2022-10-11',
            day: 2,
            month: 10,
            total: 13,
            week: 42,
            year: 2022,
            count: 14,
            codeCount: 13,
            githubCount: 1,
          },
          {
            date: '2022-10-12',
            day: 3,
            month: 10,
            total: 11,
            week: 42,
            year: 2022,
            count: 20,
            codeCount: 11,
            githubCount: 9,
          },
          {
            date: '2022-10-13',
            day: 4,
            month: 10,
            total: 6,
            week: 42,
            year: 2022,
            count: 14,
            codeCount: 6,
            githubCount: 8,
          },
          {
            date: '2022-10-14',
            day: 5,
            month: 10,
            total: 33,
            week: 42,
            year: 2022,
            count: 44,
            codeCount: 33,
            githubCount: 11,
          },
          {
            date: '2022-10-15',
            day: 6,
            month: 10,
            total: 0,
            week: 42,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
        ],
      },
      {
        week: 43,
        days: [
          {
            date: '2022-10-16',
            day: 0,
            month: 10,
            total: 0,
            week: 43,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
          {
            date: '2022-10-17',
            day: 1,
            month: 10,
            total: 6,
            week: 43,
            year: 2022,
            count: 13,
            codeCount: 6,
            githubCount: 7,
          },
          {
            date: '2022-10-18',
            day: 2,
            month: 10,
            total: 12,
            week: 43,
            year: 2022,
            count: 16,
            codeCount: 12,
            githubCount: 4,
          },
          {
            date: '2022-10-19',
            day: 3,
            month: 10,
            total: 13,
            week: 43,
            year: 2022,
            count: 20,
            codeCount: 13,
            githubCount: 7,
          },
          {
            date: '2022-10-20',
            day: 4,
            month: 10,
            total: 9,
            week: 43,
            year: 2022,
            count: 19,
            codeCount: 9,
            githubCount: 10,
          },
          {
            date: '2022-10-21',
            day: 5,
            month: 10,
            total: 2,
            week: 43,
            year: 2022,
            count: 14,
            codeCount: 2,
            githubCount: 12,
          },
          {
            date: '2022-10-22',
            day: 6,
            month: 10,
            total: 0,
            week: 43,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
        ],
      },
      {
        week: 44,
        days: [
          {
            date: '2022-10-23',
            day: 0,
            month: 10,
            total: 0,
            week: 44,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-10-24',
            day: 1,
            month: 10,
            total: 0,
            week: 44,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-10-25',
            day: 2,
            month: 10,
            total: 3,
            week: 44,
            year: 2022,
            count: 4,
            codeCount: 3,
            githubCount: 1,
          },
          {
            date: '2022-10-26',
            day: 3,
            month: 10,
            total: 9,
            week: 44,
            year: 2022,
            count: 9,
            codeCount: 9,
            githubCount: 0,
          },
          {
            date: '2022-10-27',
            day: 4,
            month: 10,
            total: 0,
            week: 44,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
          {
            date: '2022-10-28',
            day: 5,
            month: 10,
            total: 2,
            week: 44,
            year: 2022,
            count: 3,
            codeCount: 2,
            githubCount: 1,
          },
          {
            date: '2022-10-29',
            day: 6,
            month: 10,
            total: 0,
            week: 44,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
        ],
      },
      {
        week: 45,
        days: [
          {
            date: '2022-10-30',
            day: 0,
            month: 10,
            total: 0,
            week: 45,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-10-31',
            day: 1,
            month: 10,
            total: 9,
            week: 45,
            year: 2022,
            count: 17,
            codeCount: 9,
            githubCount: 8,
          },
          {
            date: '2022-11-01',
            day: 2,
            month: 11,
            total: 8,
            week: 45,
            year: 2022,
            count: 14,
            codeCount: 8,
            githubCount: 6,
          },
          {
            date: '2022-11-02',
            day: 3,
            month: 11,
            total: 0,
            week: 45,
            year: 2022,
            count: 4,
            codeCount: 0,
            githubCount: 4,
          },
          {
            date: '2022-11-03',
            day: 4,
            month: 11,
            total: 10,
            week: 45,
            year: 2022,
            count: 17,
            codeCount: 10,
            githubCount: 7,
          },
          {
            date: '2022-11-04',
            day: 5,
            month: 11,
            total: 0,
            week: 45,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-11-05',
            day: 6,
            month: 11,
            total: 11,
            week: 45,
            year: 2022,
            count: 13,
            codeCount: 11,
            githubCount: 2,
          },
        ],
      },
      {
        week: 46,
        days: [
          {
            date: '2022-11-06',
            day: 0,
            month: 11,
            total: 0,
            week: 46,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-11-07',
            day: 1,
            month: 11,
            total: 2,
            week: 46,
            year: 2022,
            count: 8,
            codeCount: 2,
            githubCount: 6,
          },
          {
            date: '2022-11-08',
            day: 2,
            month: 11,
            total: 8,
            week: 46,
            year: 2022,
            count: 13,
            codeCount: 8,
            githubCount: 5,
          },
          {
            date: '2022-11-09',
            day: 3,
            month: 11,
            total: 6,
            week: 46,
            year: 2022,
            count: 8,
            codeCount: 6,
            githubCount: 2,
          },
          {
            date: '2022-11-10',
            day: 4,
            month: 11,
            total: 26,
            week: 46,
            year: 2022,
            count: 31,
            codeCount: 26,
            githubCount: 5,
          },
          {
            date: '2022-11-11',
            day: 5,
            month: 11,
            total: 13,
            week: 46,
            year: 2022,
            count: 13,
            codeCount: 13,
            githubCount: 0,
          },
          {
            date: '2022-11-12',
            day: 6,
            month: 11,
            total: 21,
            week: 46,
            year: 2022,
            count: 34,
            codeCount: 21,
            githubCount: 13,
          },
        ],
      },
      {
        week: 47,
        days: [
          {
            date: '2022-11-13',
            day: 0,
            month: 11,
            total: 3,
            week: 47,
            year: 2022,
            count: 4,
            codeCount: 3,
            githubCount: 1,
          },
          {
            date: '2022-11-14',
            day: 1,
            month: 11,
            total: 2,
            week: 47,
            year: 2022,
            count: 8,
            codeCount: 2,
            githubCount: 6,
          },
          {
            date: '2022-11-15',
            day: 2,
            month: 11,
            total: 13,
            week: 47,
            year: 2022,
            count: 16,
            codeCount: 13,
            githubCount: 3,
          },
          {
            date: '2022-11-16',
            day: 3,
            month: 11,
            total: 11,
            week: 47,
            year: 2022,
            count: 16,
            codeCount: 11,
            githubCount: 5,
          },
          {
            date: '2022-11-17',
            day: 4,
            month: 11,
            total: 4,
            week: 47,
            year: 2022,
            count: 5,
            codeCount: 4,
            githubCount: 1,
          },
          {
            date: '2022-11-18',
            day: 5,
            month: 11,
            total: 0,
            week: 47,
            year: 2022,
            count: 3,
            codeCount: 0,
            githubCount: 3,
          },
          {
            date: '2022-11-19',
            day: 6,
            month: 11,
            total: 0,
            week: 47,
            year: 2022,
            count: 1,
            codeCount: 0,
            githubCount: 1,
          },
        ],
      },
      {
        week: 48,
        days: [
          {
            date: '2022-11-20',
            day: 0,
            month: 11,
            total: 0,
            week: 48,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-11-21',
            day: 1,
            month: 11,
            total: 11,
            week: 48,
            year: 2022,
            count: 13,
            codeCount: 11,
            githubCount: 2,
          },
          {
            date: '2022-11-22',
            day: 2,
            month: 11,
            total: 12,
            week: 48,
            year: 2022,
            count: 14,
            codeCount: 12,
            githubCount: 2,
          },
          {
            date: '2022-11-23',
            day: 3,
            month: 11,
            total: 4,
            week: 48,
            year: 2022,
            count: 15,
            codeCount: 4,
            githubCount: 11,
          },
          {
            date: '2022-11-24',
            day: 4,
            month: 11,
            total: 12,
            week: 48,
            year: 2022,
            count: 22,
            codeCount: 12,
            githubCount: 10,
          },
          {
            date: '2022-11-25',
            day: 5,
            month: 11,
            total: 12,
            week: 48,
            year: 2022,
            count: 15,
            codeCount: 12,
            githubCount: 3,
          },
          {
            date: '2022-11-26',
            day: 6,
            month: 11,
            total: 1,
            week: 48,
            year: 2022,
            count: 2,
            codeCount: 1,
            githubCount: 1,
          },
        ],
      },
      {
        week: 49,
        days: [
          {
            date: '2022-11-27',
            day: 0,
            month: 11,
            total: 0,
            week: 49,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-11-28',
            day: 1,
            month: 11,
            total: 0,
            week: 49,
            year: 2022,
            count: 7,
            codeCount: 0,
            githubCount: 7,
          },
          {
            date: '2022-11-29',
            day: 2,
            month: 11,
            total: 0,
            week: 49,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
          {
            date: '2022-11-30',
            day: 3,
            month: 11,
            total: 8,
            week: 49,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
          {
            date: '2022-12-01',
            day: 4,
            month: 12,
            total: 7,
            week: 49,
            year: 2022,
            count: 19,
            codeCount: 7,
            githubCount: 12,
          },
          {
            date: '2022-12-02',
            day: 5,
            month: 12,
            total: 6,
            week: 49,
            year: 2022,
            count: 11,
            codeCount: 6,
            githubCount: 5,
          },
          {
            date: '2022-12-03',
            day: 6,
            month: 12,
            total: 0,
            week: 49,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 50,
        days: [
          {
            date: '2022-12-04',
            day: 0,
            month: 12,
            total: 0,
            week: 50,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-12-05',
            day: 1,
            month: 12,
            total: 5,
            week: 50,
            year: 2022,
            count: 5,
            codeCount: 5,
            githubCount: 0,
          },
          {
            date: '2022-12-06',
            day: 2,
            month: 12,
            total: 15,
            week: 50,
            year: 2022,
            count: 22,
            codeCount: 15,
            githubCount: 7,
          },
          {
            date: '2022-12-07',
            day: 3,
            month: 12,
            total: 42,
            week: 50,
            year: 2022,
            count: 43,
            codeCount: 42,
            githubCount: 1,
          },
          {
            date: '2022-12-08',
            day: 4,
            month: 12,
            total: 1,
            week: 50,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
          {
            date: '2022-12-09',
            day: 5,
            month: 12,
            total: 11,
            week: 50,
            year: 2022,
            count: 11,
            codeCount: 11,
            githubCount: 0,
          },
          {
            date: '2022-12-10',
            day: 6,
            month: 12,
            total: 0,
            week: 50,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
        ],
      },
      {
        week: 51,
        days: [
          {
            date: '2022-12-11',
            day: 0,
            month: 12,
            total: 0,
            week: 51,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-12-12',
            day: 1,
            month: 12,
            total: 2,
            week: 51,
            year: 2022,
            count: 2,
            codeCount: 2,
            githubCount: 0,
          },
          {
            date: '2022-12-13',
            day: 2,
            month: 12,
            total: 19,
            week: 51,
            year: 2022,
            count: 20,
            codeCount: 19,
            githubCount: 1,
          },
          {
            date: '2022-12-14',
            day: 3,
            month: 12,
            total: 13,
            week: 51,
            year: 2022,
            count: 15,
            codeCount: 13,
            githubCount: 2,
          },
          {
            date: '2022-12-15',
            day: 4,
            month: 12,
            total: 0,
            week: 51,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-12-16',
            day: 5,
            month: 12,
            total: 0,
            week: 51,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-12-17',
            day: 6,
            month: 12,
            total: 0,
            week: 51,
            year: 2022,
            count: 2,
            codeCount: 0,
            githubCount: 2,
          },
        ],
      },
      {
        week: 52,
        days: [
          {
            date: '2022-12-18',
            day: 0,
            month: 12,
            total: 0,
            week: 52,
            year: 2022,
            count: 0,
            codeCount: 0,
            githubCount: 0,
          },
          {
            date: '2022-12-19',
            day: 1,
            month: 12,
            total: 14,
            week: 52,
            year: 2022,
            count: 20,
            codeCount: 14,
            githubCount: 6,
          },
          {
            date: '2022-12-20',
            day: 2,
            month: 12,
            total: 4,
            week: 52,
            year: 2022,
            count: 6,
            codeCount: 4,
            githubCount: 2,
          },
          {
            date: '2022-12-21',
            day: 3,
            month: 12,
            total: 6,
            week: 52,
            year: 2022,
            count: 7,
            codeCount: 6,
            githubCount: 1,
          },
          {
            date: '2022-12-22',
            day: 4,
            month: 12,
            total: 1,
            week: 52,
            year: 2022,
            count: 8,
            codeCount: 1,
            githubCount: 7,
          },
          {
            date: '2022-12-23',
            day: 5,
            month: 12,
            total: 1,
            week: 52,
            year: 2022,
            count: 1,
            codeCount: 1,
            githubCount: 0,
          },
          {
            date: '2022-12-24',
            day: 6,
            month: 12,
            total: 33,
            week: 52,
            year: 2022,
            count: 33,
            codeCount: 33,
            githubCount: 0,
          },
        ],
      },
      {
        week: 53,
        days: [
          {
            date: '2022-12-25',
            day: 0,
            month: 12,
            total: 20,
            week: 53,
            year: 2022,
            count: 20,
            codeCount: 20,
            githubCount: 0,
          },
          {
            date: '2022-12-26',
            day: 1,
            month: 12,
            total: 11,
            week: 53,
            year: 2022,
            count: 11,
            codeCount: 11,
            githubCount: 0,
          },
          {
            date: '2022-12-27',
            day: 2,
            month: 12,
            total: 14,
            week: 53,
            year: 2022,
            count: 14,
            codeCount: 14,
            githubCount: 0,
          },
          {
            date: '2022-12-28',
            day: 3,
            month: 12,
            total: 8,
            week: 53,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
          {
            date: '2022-12-29',
            day: 4,
            month: 12,
            total: 8,
            week: 53,
            year: 2022,
            count: 8,
            codeCount: 8,
            githubCount: 0,
          },
          {
            date: '2022-12-30',
            day: 5,
            month: 12,
            total: 53,
            week: 53,
            year: 2022,
            count: 53,
            codeCount: 53,
            githubCount: 0,
          },
        ],
      },
    ],
  });
}
